language: node_js
node_js:
- '5'
- '4'
- '0.12'
- '0.11'
- '0.10'
- iojs-v1
- iojs-v2
- iojs-v3
script: npm test
before_script:
- gulp -v
- rm -fR ./node_modules
- npm i -g npm
- npm -v
- npm install
after_success:
- ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
