language: node_js
node_js:
- '5'
- '4'
- '0.12'
- '0.11'
- '0.10'
- iojs-v1
- iojs-v2
- iojs-v3
script: npm test
before_script:
- gulp -v
- rm -fR ./node_modules
- npm i -g npm
- npm -v
- npm install
after_success:
- ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
addons:
  code_climate:
    repo_token: 18c3ab76d6a7293eb6538ebc315dfea5170289a57017b8857dc0b89012d5ff40
branches:
  only:
    - master
    - develop
